# Configuration details: https://github.com/landscapeio/landscape-docs/blob/master/configuration.rst
autodetect: yes
doc-warnings: yes
max-line-length: 80
pep257:
    disable:
        - D203
pep8:
    full: tr;ue
ignore-paths:
    - app/test/
python-targets:
    - 3
requirements:
    - requirements.txt
strictness: veryhigh
test-warnings: yes
