DATADIR=data
MATRIXANALYSERDIR=$(DATADIR)/matrixanalyser
FIGURESDIR=$(MATRIXANALYSERDIR)/figures

matrixanalyser:
	-@mkdir $(DATADIR) 2>/dev/null || true
	-@mkdir $(MATRIXANALYSERDIR) 2>/dev/null || true
	-@mkdir $(FIGURESDIR) 2>/dev/null || true

clean:
	-@rm -f $(DATADIR) 2>/dev/null || true
